### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'autoreconnect'!

### ISSUE THREAD

**Issue by harvanchik** [Bstn1802/AutoReconnect#13]
Game crashing on launch.  Tried with Mod Menu 2.0.5, 2.0.4, and without it entirely.

Auto Reconnect version: 1.3.0
Minecraft version: 1.17.1

Log: <https://pastebin.com/6XTY0ifN>

Other mods I had enabled.
![image](https://user-images.githubusercontent.com/66141166/130140677-56ed9fbb-808c-47f4-95df-9adda02d8cda.png)

**Comment by Bstn1802** [comment]
Noted. You are actually not the only one with this issue, but the problem is that its working completely fine for me (with and without modmenu) and I have no clue as to why its crashing for you, sorry
Ill try to get some help from other developers and fix this problem asap

**Comment by harvanchik** [comment]
> Noted. You are actually not the only one with this issue, but the problem is that its working completely fine for me (with and without modmenu) and I have no clue as to why its crashing for you, sorry
> 
> Ill try to get some help from other developers and fix this problem asap
> 
> 

Thank you. That's odd that it's not working for me, but is for you. It wouldn't happen to be the Java version being different would it?  Just spit-balling. I really like this mod because it makes developing Minecraft plugins more efficient. I don't have to relog every time I restart the server.

**Comment by Bstn1802** [comment]
Some mod I used included Cloth Config API which is necessary for this mod to work now that Im using it. I was wondering why I didnt need to add it, but it seems like another mod that I was using includes cloth config and none of your mods does. So you need to add the [Cloth Config API](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files) and then it should work. Ill add the dependency later and the game should not just crash but instead tell you, that that mod is missing.

**Comment by harvanchik** [comment]
You should include that the Cloth Config API mod is required in the ReadMe.

**Comment by Bstn1802** [comment]
It does on the curseforge page which I'm updating primarily and I only have the ReadMe and releases here as well because thats just a thing I can do and the source code is here anyway, but it's redundant really and I often forget to update them.
With the latest release v1.3.1 ClothConfig has been added to the dependencies list so the game should not just crash but instead tell you that that mod is missing.
