### ISSUE TITLE
Config is reset every time game launches.

### ISSUE THREAD

**Issue by harvanchik** [Bstn1802/AutoReconnect#14]
This may be a new bug since the config file was changed.  After manually editing the config, when the game launches, it resets to the default values.  Also, after editing the times using the mod menu, the config is reset when the game re-launches.

**Comment by Bstn1802** [comment]
Thanks for opening this issue, I probably would'nt have noticed. I could reproduce the error and I changed a few things in the config that I think caused the issue and now it seems to work for me. Would be great if you could confirm that so I can close this issue. There should be a new release (version 1.3.1) on curseforge and Ill upload it here too now.

**Comment by harvanchik** [comment]
I will try it out later once I get off work.

**Comment by harvanchik** [comment]
Yep, [v1.3.1](https://github.com/Bstn1802/AutoReconnect/releases/tag/v1.3.1) has fixed the issue!  Thanks a ton.
