### ISSUE TITLE
Crash in Mod Menu

### ISSUE THREAD

**Issue by Toseflo** [Bstn1802/AutoReconnect#15]
When you select AutoReconnect in ModMenu, the game crashes.
I tested it with a new instance of Minecraft and only the lastest versions of AutoReconnect, ModMenu, Fabric API and Cloth Config API installed.
[crash-2021-09-05_19.52.17-client.txt](https://github.com/Bstn1802/AutoReconnect/files/7112093/crash-2021-09-05_19.52.17-client.txt)

**Comment by Bstn1802** [comment]
Thanks for opening this issue :) I actually had that issue in the back of my mind but I forgot about it and didn't check if I need to do something about it when I released v1.3.1 but it should now be fixed with the latest release v1.3.2!
