### ISSUE TITLE
Auto Reconnect trigging while in server.

### ISSUE THREAD

**Issue by DevFizzie** [Bstn1802/AutoReconnect#21]
I have been having an issue where I would get the screen like it is joining a server even though I was already in a server. I believe it is the mod cause when I remove it, it doesn't happen. It doesn't happen a lot but it still happens every so often which can be annoying when your dueling someone. .-.

**Comment by Bstn1802** [comment]
Thanks for letting me know, I'll definitely look into that later, not sure when I'll be able to fix it though, depends on whether I'll be able to reproduce this. Can you tell me how it "doesn't happen a lot", like when _does_ it happen, any idea? Any connection there might be? And how long after joining the server does it happen? Could it be, that the countdown is mistakenly still running in the background and then reconnecting you although you already are connected? Was it even a reconnect or did you just join and then it randomly happens? Are you on a modded server switching worlds? Maybe that's triggering something...

**Comment by DevFizzie** [comment]
I have no clue how it happens, it just randomly happens somewhat often.
