### ISSUE TITLE
I Think that´s a bug 

### ISSUE THREAD

**Issue by Belu97** [Bstn1802/AutoReconnect#26]
![image](https://user-images.githubusercontent.com/101136394/176430955-6616f128-d977-45ab-bd64-6b6598818385.png)
i want to make a auto command but it doesn't work

**Comment by Bstn1802** [comment]
You're right and I already found out why: It seems like in 1.19 it makes a difference whether you send a normal chat message or a command. Should be quite easy to fix tho, just check if the message starts with a slash I guess, if it does, say it's supposed to be a command.
