### ISSUE TITLE
[FEATURE REQUEST] add a total number of reconnects toggle

### ISSUE THREAD

**Issue by RedstoneManiac3Xbox** [Bstn1802/AutoReconnect#30]
say I don't want to reconnect until I come back to the computer and disable it, but I only want to reconnect a certain number of times or for a certain amount of time (say 3 hours) you add an option to limit the total number of reconnects, and make it so you could either do; number of minutes (or hours) before reconnect attempts are stopped, or a number of total (successful) reconnects are made.
so:
Stop Reconnecting after:  [3 button cycle] {Off} {Time} {# of attempts}
Time: 3 hours (180 min)
Number of Attempts: 15
would that be possible?
I don't want to afk all night but I don't know how to make my laptop sleep after a certain amount of time while closed. i just think this would be a neat addition and would make the process easier.

**Comment by Bstn1802** [comment]
Sorry for the late response. I don't think this is something that should be handled by this mod. If you only want to afk for a certain amount of time, limiting the amounts of reconnects wouldn't control that and limiting the amount of time you're afk is not the purpose of this mod, it doesn't even know when your afk or for how long.

It should be possible to set up some sort of automation on your device that will either just shutdown your device or even disconnect you from your world and close minecraft before shutting down. While that could also be done in form of a mod, setting up a countdown and disconnecting automatically, I don't think this is a job for a mod that has the purpose to reconnect automatically (it's quite the opposite).
Also would blow up the configuration quite a lot I imagine
