### ISSUE TITLE
Auto Message not working

### ISSUE THREAD

**Issue by codefreak558** [Bstn1802/AutoReconnect#39]
I am trying to get auto message to work with the current source code as the fix for commands is not out yet and once I eventually got it built I boot up Minecraft and the autoreconnect part of it worked but it did not send and messages, so to check my basis I used the current release and that also doesnt even send messages not commands as that doesnt work on 2.1.0-dev.

So am I doing something wrong or is there a specific way that you need to type in the server/world it targets?

**Comment by pizzaman21223** [comment]
Having the same issue with this.
![image](https://user-images.githubusercontent.com/122572870/212188024-2b367af0-08eb-4395-96de-a183a400bc1e.png)

**Comment by codefreak558** [comment]
@Bstn1802 Don't worry I no longer have the config on my pc

**Comment by Bstn1802** [comment]
Okay, I'm closing this issue then. This had to be quite an old version too back in January and is probably not relevant anymore :'D
