### ISSUE TITLE
Publish the mod on the Modrinth platform

### ISSUE THREAD

**Issue by TechPro424** [Bstn1802/AutoReconnect#44]
Please consider publishing the mod on the [Modrinth platform](https://modrinth.com/) as it provides a better user experience, in my honest opinion

**Comment by Bstn1802** [comment]
Seeing that ModMenu can automatically inform users about updates by checking for the latest version on modrinth, I had the feeling it would be worth it.

Also now that I used Modrinth a bit, I can see how people find it a better user experience, although I would argue you need to get used to it and get a hang of where to find specific things.

It's already such an improvement tho that the description supports markdown and renders properly. Always having issues with my description on curseforge not looking how I want it to. Then modmenu's update tracker ofc. I'm starting to like that platform.

The project page is currently still under review, but it should be public soon: https://modrinth.com/mod/autoreconnect
