### ISSUE TITLE
Q: How to i get this mod to work in 1.19.4

### ISSUE THREAD

**Issue by Elilidagamer** [Bstn1802/AutoReconnect#47]
Is there some sort of way for you to send a 1.19.4 updated version of this? i cant seem to figure out how to make it work at all

**Comment by Elilidagamer** [comment]
please i made an account for this single auto reconnect mod becaus there isnt a single one in the world thats 1.19.4

**Comment by Bstn1802** [comment]
There's gonna be a 1.19.4 version eventually, just a little busy atm

**Comment by Elilidagamer** [comment]
thanks so much, please send a message whenever you get it to work, im dying to get this and i dont know how to do more than just download and drag it into a folder lol
