### ISSUE TITLE
1.19.4 support

### ISSUE THREAD

**Issue by TechPro424** [Bstn1802/AutoReconnect#48]
Being worked on in #46

**Comment by Bstn1802** [comment]
@James-P-Bennett The messages you posted are completely normal. When the mod cannot load the config file it logs a message together with the exception it got while trying to open it. In this case the config file didn't exist. As soon as you make changes to the default configuration and click save, a configuration file should be saved to the config folder.

**Comment by Bstn1802** [comment]
Closing this issue, as I am focusing on the 1.20 update right now (and 1.20.1 next if there's anything to be done)
If there's need for a version for 1.19.3/4 feel free to reopen (which should be possible, otherwise open a new issue)

**Comment by ghost** [comment]
Can this please be reopened? a lot of servers are not moving to 1.20.X and are staying on 1.19.4.

**Comment by Bstn1802** [comment]
Would an unofficial version be enough?
You can find a build of the update made by TechPro here: https://github.com/Bstn1802/AutoReconnect/pull/46#issuecomment-1502827817
I didn't end up merging it, as by the time I got to look into it 1.20 had already released, so I merged another PR for 1.20 instead and worked on releasing a version for 1.20.
I did look into TechPros update tho and tested it and it works fine.

**Comment by ghost** [comment]
For sure would work

**Comment by ghost** [comment]
> Would an unofficial version be enough?
> You can find a build of the update made by TechPro here: https://github.com/Bstn1802/AutoReconnect/pull/46#issuecomment-1502827817
> I didn't end up merging it, as by the time I got to look into it 1.20 had already released, so I merged another PR for 1.20 instead and worked on releasing a version for 1.20.
> I did look into TechPros update tho and tested it and it works fine.

Only thing I cannot get to work with his version is the auto join message.

**Comment by Bstn1802** [comment]
Works fine for me, both messages and commands, in both singleplayer and multiplayer, only couldn't test it in realms.
What are you trying to reconnect to? How is the config set up? Did it use to work with older versions the way your config is set up?

**Comment by ghost** [comment]
> Works fine for me, both messages and commands, in both singleplayer and multiplayer, only couldn't test it in realms. What are you trying to reconnect to? How is the config set up? Did it use to work with older versions the way your config is set up?

Instead of explaining I just took a screenshot of my setup. I have it on a 10 second delay after joining the server but it does not do anything after I join, I sat there for a whole 2 minutes just in case. It should be typing /oneblock upon joining, or do I have it set wrong? Here is the screenshot btw. https://i.imgur.com/tLWDGuA.png

Also, I never really had too much of a use for this in the last few versions so haven't used it. But I seem to remember it working like this. I could be wrong and remembering it wrong though.

**Comment by Bstn1802** [comment]
If `Bosscraft.net` is the name you gave that server when adding it to the multiplayer screen I don't see a reason why it shouldn't work.
Anything suspicious in the logs?
Can you test on other servers and see if it works?

**Comment by ghost** [comment]
> If `Bosscraft.net` is the name you gave that server when adding it to the multiplayer screen I don't see a reason why it shouldn't work. Anything suspicious in the logs? Can you test on other servers and see if it works?

Ahhh, I see what I did wrong here... User error on my part. I put .com in the name and not .net... I feel incredibly stupid right now wasting your time. Sorry about that.
