### ISSUE TITLE
Compile mod for older versions.

### ISSUE THREAD

**Issue by strelokhalfer** [Bstn1802/AutoReconnect#7]
Many players still prefer to play older versions of Minecraft(like 1.12.2 and 1.7.10), it would be nice to give them another useful mod.

**Comment by zatrit** [comment]
This mod using Fabric, but 1.7 and 1.12 using Forge.
Fabric and Forge are diferent mod loaders

**Comment by strelokhalfer** [comment]
Oh, I see. I'll try to rewrite it for Forge myself.
